export const CUISINE_OPTIONS = [
  "Karinderya",
  "Carinderia",
  "Pungko-Pungko",
  "Turo-Turo",
  "Silogan",
  "Lugawan",
  "Paresan",
  "Ihawan",
  "Inasal House",
  "Lechon House",
  "Seafood Dampa",
  "Eatery",
  "Canteen",
  "Food Court Stall",
  "Street Food Stall",
  "Night Market Stall",
  "Sari-Sari Store (with food)",
  "Cafe",
  "Coffee Shop",
  "Milk Tea Shop",
  "Bakery",
  "Pastry Shop",
  "Dessert Shop",
  "Halo-Haloan",
  "Juice Bar",
  "Fast Food",
  "Casual Dining Restaurant",
  "Fine Dining Restaurant",
  "Buffet Restaurant",
  "Family Restaurant",
  "Theme Restaurant",
  "Food Truck",
  "Pop-up Kitchen",
  "Cloud Kitchen / Ghost Kitchen",
  "Bar",
  "Restobar",
  "KTV Bar",
  "Beerhouse",
  "Fish Ball Stall",
  "Kwek-Kwek Stall",
  "Tempura Stall",
  "Isaw Stall",
  "Betamax Stall",
  "Adidas Stall",
  "Walkman Stall",
  "Helmet Stall",
  "Banana Cue Stall",
  "Kamote Cue Stall",
  "Turon Stall",
  "Maruya Stall",
  "Balut Stall",
  "Penoy Stall",
  "Mais Stall",
  "Dirty Ice Cream Stall",
  "Ice Scramble Stall",
  "Buko Juice Stand",
  "Sugarcane Juice Stand",
  "Palamig Stand",
  "Hotdog on Stick Stall",
  "Burger Stand",
  "Fries Stand",
  "Shawarma Stand",
  "Siomai Stall",
  "Siopao Stand",
  "Takoyaki Stall",
  "Samgyupsal Unlimited",
  "Unli Wings",
  "Unli Seafood Boil",
  "Mukbang Food Tray",
  "Boodle Fight Setup",
  "Sushi Bake Shop",
  "Takoyaki Overload",
  "Loaded Fries Bar",
  "Overload Burger Joint",
  "Cheesy Street Food Stall",
  "Flavored Wings Hub",
  "Chicken Skin Station",
  "Milktea + Takoyaki Combo Shop",
  "Korean Corn Dog Shop",
  "Mozzarella Stick Stand",
  "Ramen Bar",
  "DIY Samgyup Grill",
  "Hotpot Unlimited",
  "Street Food Platter Shop",
  "Rice Meal Box Concept",
  "Budget Rice Toppings Bar",
  "Aesthetic Cafe",
  "Minimalist Cafe",
  "Plant Cafe",
  "Co-working Cafe",
  "Pet Cafe",
  "Dessert Buffet Cafe",
  "Croffle Shop",
  "Souffle Pancake Cafe",
  "Basque Cheesecake Shop",
  "Ube Dessert Shop",
  "Matcha Cafe",
];
