export const CUISINE_OPTIONS = [
  // Filipino / Local Concepts
  "Karinderya",
  "Pungko-Pungko",
  "Turo-Turo",
  "Silogan",
  "Lugawan",
  "Paresan",
  "Sisigan",
  "Bulalohan",
  "Gotohan",
  "Mami House",
  "Panciteria",
  "Palabokan",
  "Tuslob Buwa-an",
  "Ihawan",
  "Inasal House",
  "Lechon House",
  "Seafood House",
  "Grill House",

  // Restaurant / Dining Types
  "Eatery",
  "Canteen",
  "Food Stall",
  "Food Court Stall",
  "Street Food Stall",
  "Night Market Stall",
  "Market Stall",
  "Sari-Sari Store (with food)",
  "Cafe",
  "Coffee Shop",
  "Milk Tea Shop",
  "Tea House",
  "Bakery",
  "Pastry Shop",
  "Dessert Shop",
  "Juice Bar",
  "Smoothie Bar",
  "Fast Food Restaurant",
  "Casual Dining Restaurant",
  "Fine Dining Restaurant",
  "Buffet Restaurant",
  "Family Restaurant",
  "Theme Restaurant",
  "Food Truck",
  "Pop-up Kitchen",
  "Cloud Kitchen / Ghost Kitchen",
  "Takeout Counter",
  "Drive-Thru",
  "Deli",
  "Bistro",
  "Bar",
  "Restobar",
  "KTV Bar",
  "Sports Bar",
  "Beer Garden",

  // General Food Stall Types
  "BBQ Stall",
  "Grilled Food Stall",
  "Fried Food Stall",
  "Rice Meal Stall",
  "Rice Toppings Stall",
  "Rice Bowl Stall",
  "Noodle Stall",
  "Soup Stall",
  "Snack Stall",
  "Dessert Stall",
  "Seafood Stall",
  "Chicken Stall",
  "Burger Stall",
  "Hotdog Stall",
  "Sandwich Stall",
  "Pizza Stall",
  "Street BBQ Stall",
  "Skewer Stall",
  "Kiosk",
  "Snack Cart",
  "Mobile Food Cart",
  "Drink Stand",
  "Coffee Stand",
  "Juice Stand",
  "Shake Stand",
  "Milk Tea Stand",
  "Ice Cream Stall",

  // Asian Concepts
  "Samgyupsal Restaurant",
  "Ramen Bar",
  "Sushi Bar",
  "Tempura House",
  "Takoyaki Shop",
  "Dim Sum House",
  "Hotpot Restaurant",
  "Shabu-Shabu Restaurant",

  // Western / Modern Concepts
  "Burger Joint",
  "Steakhouse",
  "Wing House",
  "Seafood Boil Restaurant",
  "Pasta House",
  "Pizza Parlor",
  "Chicken House",
  "All-Day Breakfast Restaurant",

  // Specialty Cafes
  "Aesthetic Cafe",
  "Minimalist Cafe",
  "Plant Cafe",
  "Co-working Cafe",
  "Pet Cafe",
  "Dessert Cafe",
  "Book Cafe",
  "Gaming Cafe",
  "Internet Cafe",
  "Art Cafe",

  "Other",
];